#!/bin/bash
#SBATCH --job-name=mesh_splatting
#SBATCH --chdir=/home/KnapikE/mesh-splatting
#SBATCH --partition=rtx40
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --output=output/pipeline.%j.out
#SBATCH --error=error/pipeline.%j.err
export LD_LIBRARY_PATH=/home/KnapikE/micromamba/envs/trace3d/lib:$LD_LIBRARY_PATH

# --- 2. EXECUTION PIPELINE ---
# We use '|| exit 1' to stop the job immediately if a step fails.
dataset=./
path=~/input/${dataset}
scene='POLY_01' 

output=./output/${dataset}/${scene} 
source=${path}/${scene}


echo "[4/4] Contrastive lifting..."
python train_contrastive.py -s ${source} -m ${output} --iterations 20000 --start_checkpoint ${output}/point_cloud/iteration_chkpt_9000/point_cloud_state_dict.pt --sam_folder split_ms --include_feature --save_name sp_ --instance_feature_lr 0.05 --instance_feature_nbr 3 --sample_num 4096|| exit 1

echo "=========================================="
echo "Pipeline Completed Successfully!"
echo "=========================================="