#!/bin/bash
#SBATCH --job-name=mesh_splatting
#SBATCH --chdir=/home/KnapikE/mesh-splatting
#SBATCH --partition=rtx50
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --output=output/pipeline.%j.out
#SBATCH --error=error/pipeline.%j.err
export LD_LIBRARY_PATH=/home/KnapikE/micromamba/envs/trace3d/lib:$LD_LIBRARY_PATH

# --- 2. EXECUTION PIPELINE ---
# We use '|| exit 1' to stop the job immediately if a step fails.
dataset=custom
path=~/input/${dataset}
scene='casque' 

output=./output/${dataset}/${scene} 
source=${path}/${scene}


echo "[1/4] Scene reconstruction (train_rgb)..."
python train.py -s ${source} -m ${output} --eval --indoor --iterations 30000 || exit 1

echo "[2/4] Merge patch masks..."
#python merge_patches.py -s ${source}  -m ${output} || exit 1
 
echo "[3/4] Delete Ambiguous Gaussians..."
#python remove_ab_triangles.py -s ${source} -m ${output} --sam_folder split_ms --iterations 9000 --prune --eval|| exit 1

echo "[4/4] Contrastive lifting..."
#python train_contrastive.py -s ${source} -m ${output} --iterations 20000 --start_checkpoint ${output}/point_cloud/iteration_chkpt_9000/point_cloud_state_dict.pt --sam_folder split_ms --include_feature --save_name sp_ --save_iteration 20000 50000 --eval || exit 1

echo "=========================================="
echo "Pipeline Completed Successfully!"
echo "=========================================="