#!/bin/bash
#SBATCH --job-name=mesh_splatting
#SBATCH --chdir=/home/KnapikE/mesh-splatting/
#SBATCH --partition=rtx30
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --output=output/output.%N.%J.%u.txt
#SBATCH --error=error/error.%N.%J.%u.txt


python train_contrastive.py -s ~/input/nerf_synthetic/hotdog -m output/hotdog/ --sam_folder split --iterations 20000 --start_checkpoint output/hotdog/point_cloud/iteration_chkpt_9000/point_cloud_state_dict.pt --sam_folder split --include_feature --save_name sp_ --instance_feature_lr 0.05 --instance_feature_nbr 16
wait


