#!/bin/bash
#SBATCH --job-name=mesh_splatting
#SBATCH --chdir=/home/KnapikE/mesh-splatting
#SBATCH --partition=rtxpro
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=10
#SBATCH --nodes=1
#SBATCH --output=output/pipeline.%j.out
#SBATCH --error=error/pipeline.%j.err
export LD_LIBRARY_PATH=/home/KnapikE/micromamba/envs/trace3d/lib:$LD_LIBRARY_PATH


python merge_patches.py -s ~/input/custom/Detailed\ Drum\ Set -m output/custom/Detailed\ Drum\ Set
python merge_patches.py -s ~/input/custom/indoor\ plant\ ficus/ -m output/custom/indoor\ plant\ ficus/
python merge_patches.py -s ~/input/custom/Hotdog -m output/custom/Hotdog 
python merge_patches.py -s ~/input/custom/Microphone -m output/custom/Microphone