#!/bin/bash
#SBATCH --job-name=mesh_splatting
#SBATCH --chdir=/home/KnapikE/mesh-splatting
#SBATCH --partition=rtx30
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=10
#SBATCH --nodes=1
#SBATCH --output=output/pipeline.%j.out
#SBATCH --error=error/pipeline.%j.err
export LD_LIBRARY_PATH=/home/KnapikE/micromamba/envs/trace3d/lib:$LD_LIBRARY_PATH

# --- 2. EXECUTION PIPELINE ---
# We use '|| exit 1' to stop the job immediately if a step fails.
#python metrics.py -m output/REPLICA/office_0/Sequence_1
#python metrics.py -m output/REPLICA/office_1/Sequence_1
#python metrics.py -m output/REPLICA/office_2/Sequence_1
#python metrics.py -m output/REPLICA/office_3/Sequence_1
#python metrics.py -m output/REPLICA/office_4/Sequence_1
#python metrics.py -m output/REPLICA/room_0/Sequence_1
#python metrics.py -m output/REPLICA/room_1/Sequence_1
#python metrics.py -m output/REPLICA/room_2/Sequence_1

python metrics.py -m output/custom/Detailed_Drum_Set
python metrics.py -m output/custom/indoor_plant_ficus/
python metrics.py -m output/custom/Hotdog
python metrics.py -m output/custom/Microphone