#!/bin/bash
#SBATCH --job-name=mesh_splatting
#SBATCH --chdir=/home/KnapikE/mesh-splatting
#SBATCH --partition=rtx30
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=10
#SBATCH --nodes=1
#SBATCH --output=output/pipeline.%j.out
#SBATCH --error=error/pipeline.%j.err
export LD_LIBRARY_PATH=/home/KnapikE/micromamba/envs/trace3d/lib:$LD_LIBRARY_PATH

# --- 2. EXECUTION PIPELINE ---
# We use '|| exit 1' to stop the job immediately if a step fails.
dataset=REPLICA
path=~/input/${dataset}
scene='office_0/Sequence_1' 

output=./output/${dataset}/${scene} 
source=${path}/${scene}


python create_video.py -s ${source} -m ${output}